---
deployment:
  tasks:
    - export DEPLOYPATH=/home/datauno1/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R uploads $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp catalogo.php $DEPLOYPATH
    - /bin/cp producto.php $DEPLOYPATH
    - /bin/cp desarrollo.php $DEPLOYPATH