<?php
$contacto = [
    'whatsapp' => '+56 9 9439 2133',
    'whatsapp_link' => 'https://wa.me/56994392133',
    'email' => 'victordiaz.pc@gmail.com',
    'direccion' => 'Chorrillos 1012, Victoria, Araucanía, Chile',
    'facebook' => 'https://es-la.facebook.com/datauno.cl/',
    'instagram' => 'https://instagram.com/datauno.cl',
];

$serviciosTecnicos = [
    [
        'categoria' => 'Mantención',
        'titulo' => 'Mantención preventiva',
        'descripcion' => 'Limpieza interna, revisión de temperatura, ventilación, pasta térmica y optimización general para extender la vida útil del equipo.',
        'precio' => 'Cotizar',
        'icono' => '🛠️',
        'destacado' => true,
    ],
    [
        'categoria' => 'Sistema',
        'titulo' => 'Formateo e instalación',
        'descripcion' => 'Instalación de sistema operativo, drivers, programas esenciales, configuración inicial y equipo listo para trabajar.',
        'precio' => 'Cotizar',
        'icono' => '💻',
        'destacado' => true,
    ],
    [
        'categoria' => 'Upgrade',
        'titulo' => 'Mejora SSD / RAM',
        'descripcion' => 'Actualización de disco sólido, memoria RAM y componentes para mejorar velocidad, arranque y rendimiento diario.',
        'precio' => 'Cotizar',
        'icono' => '⚡',
        'destacado' => true,
    ],
    [
        'categoria' => 'Diagnóstico',
        'titulo' => 'Diagnóstico técnico',
        'descripcion' => 'Revisión de fallas, lentitud, pantallazos, problemas de encendido, sobrecalentamiento y errores de hardware o software.',
        'precio' => 'Cotizar',
        'icono' => '🔍',
        'destacado' => false,
    ],
    [
        'categoria' => 'Datos',
        'titulo' => 'Respaldo y transferencia',
        'descripcion' => 'Respaldo de documentos, fotografías, archivos importantes y traspaso hacia otro equipo o dispositivo externo.',
        'precio' => 'Cotizar',
        'icono' => '🗂️',
        'destacado' => false,
    ],
    [
        'categoria' => 'Reparación',
        'titulo' => 'Cambio de piezas',
        'descripcion' => 'Reemplazo de discos, memorias, cargadores, teclados, pantallas, baterías y componentes según disponibilidad.',
        'precio' => 'Cotizar',
        'icono' => '🔩',
        'destacado' => false,
    ],
    [
        'categoria' => 'Optimización',
        'titulo' => 'PC lento o saturado',
        'descripcion' => 'Limpieza de programas innecesarios, ajustes de inicio, revisión de espacio, salud del disco y optimización de rendimiento.',
        'precio' => 'Cotizar',
        'icono' => '🚀',
        'destacado' => false,
    ],
    [
        'categoria' => 'Asesoría',
        'titulo' => 'Compra y armado',
        'descripcion' => 'Orientación para elegir, mejorar o armar un equipo según presupuesto, uso esperado y necesidades reales.',
        'precio' => 'Cotizar',
        'icono' => '🧩',
        'destacado' => false,
    ],
];

$serviciosDesarrollo = [
    [
        'titulo' => 'Landing pages profesionales',
        'descripcion' => 'Sitios modernos para presentar servicios, captar clientes y conectar directo con WhatsApp o correo.',
        'icono' => '🌐'
    ],
    [
        'titulo' => 'Catálogos web administrables',
        'descripcion' => 'Catálogos para mostrar productos o servicios, con estructura preparada para panel administrativo.',
        'icono' => '🛒'
    ],
    [
        'titulo' => 'Sistemas internos a medida',
        'descripcion' => 'Herramientas para ordenar procesos, registros, inventarios, solicitudes o flujos de trabajo.',
        'icono' => '🧠'
    ],
    [
        'titulo' => 'Dashboards y reportes',
        'descripcion' => 'Visualización de datos, indicadores y reportes para tomar mejores decisiones.',
        'icono' => '📊'
    ],
    [
        'titulo' => 'Automatización de procesos',
        'descripcion' => 'Reducción de tareas repetitivas mediante formularios, integraciones y flujos simples.',
        'icono' => '🤖'
    ],
    [
        'titulo' => 'Mantención web',
        'descripcion' => 'Correcciones, mejoras, optimización visual y soporte para sitios existentes.',
        'icono' => '🔧'
    ],
];

$productosCatalogo = [
    [
        'id' => 'ssd-240-480',
        'categoria' => 'Almacenamiento',
        'nombre' => 'Disco SSD 240GB / 480GB',
        'descripcion' => 'Ideal para acelerar computadores lentos, mejorar arranque y reducir tiempos de carga.',
        'detalle' => 'Instalación disponible según equipo. Capacidad y marca sujetas a stock.',
        'precio' => 'Cotizar',
        'imagen' => 'assets/img/placa-tech.jpg',
        'badge' => 'Upgrade recomendado',
        'destacado' => true,
    ],
    [
        'id' => 'ssd-1tb',
        'categoria' => 'Almacenamiento',
        'nombre' => 'Disco SSD 1TB',
        'descripcion' => 'Más espacio y velocidad para equipos de trabajo, estudio, diseño o uso diario intensivo.',
        'detalle' => 'Recomendado para notebooks y PC que necesitan mayor capacidad.',
        'precio' => 'Cotizar',
        'imagen' => 'assets/img/servicio-tecnico.jpeg',
        'badge' => 'Mayor capacidad',
        'destacado' => false,
    ],
    [
        'id' => 'ram-ddr4',
        'categoria' => 'Memorias RAM',
        'nombre' => 'Memoria RAM DDR4',
        'descripcion' => 'Mejora multitarea, navegación, programas de oficina y rendimiento general del equipo.',
        'detalle' => 'Se valida compatibilidad antes de recomendar capacidad.',
        'precio' => 'Cotizar',
        'imagen' => 'assets/img/diagnostico.jpeg',
        'badge' => 'Compatibilidad previa',
        'destacado' => true,
    ],
    [
        'id' => 'ram-ddr3',
        'categoria' => 'Memorias RAM',
        'nombre' => 'Memoria RAM DDR3',
        'descripcion' => 'Opción para equipos antiguos que todavía pueden ganar estabilidad y fluidez.',
        'detalle' => 'Sujeta a disponibilidad y revisión del modelo exacto.',
        'precio' => 'Cotizar',
        'imagen' => 'assets/img/placa-tech.jpg',
        'badge' => 'Equipos antiguos',
        'destacado' => false,
    ],
    [
        'id' => 'cargador-notebook',
        'categoria' => 'Accesorios',
        'nombre' => 'Cargadores para notebook',
        'descripcion' => 'Cargadores compatibles según voltaje, amperaje, punta y modelo del equipo.',
        'detalle' => 'Se confirma compatibilidad para evitar daños al equipo.',
        'precio' => 'Cotizar',
        'imagen' => 'assets/img/soporte-tecnico.jpg',
        'badge' => 'Según modelo',
        'destacado' => true,
    ],
    [
        'id' => 'teclado-notebook',
        'categoria' => 'Repuestos',
        'nombre' => 'Teclados para notebook',
        'descripcion' => 'Repuesto e instalación para teclados con teclas dañadas, fallas o derrames.',
        'detalle' => 'Cotización según marca, modelo y disponibilidad.',
        'precio' => 'Cotizar',
        'imagen' => 'assets/img/servicio-tecnico.jpeg',
        'badge' => 'Instalación disponible',
        'destacado' => false,
    ],
    [
        'id' => 'bateria-notebook',
        'categoria' => 'Repuestos',
        'nombre' => 'Baterías para notebook',
        'descripcion' => 'Reemplazo de batería para equipos con poca duración, hinchazón o carga irregular.',
        'detalle' => 'Se revisa modelo exacto antes de cotizar.',
        'precio' => 'Cotizar',
        'imagen' => 'assets/img/diagnostico.jpeg',
        'badge' => 'Revisión previa',
        'destacado' => false,
    ],
    [
        'id' => 'adaptadores-cables',
        'categoria' => 'Accesorios',
        'nombre' => 'Cables y adaptadores',
        'descripcion' => 'HDMI, USB, red, adaptadores de video, energía y conectividad para uso diario.',
        'detalle' => 'Disponibilidad variable según tipo de conexión.',
        'precio' => 'Cotizar',
        'imagen' => 'assets/img/soporte-tecnico.jpg',
        'badge' => 'Conectividad',
        'destacado' => false,
    ],
    [
        'id' => 'pasta-termica',
        'categoria' => 'Mantención',
        'nombre' => 'Pasta térmica y limpieza',
        'descripcion' => 'Insumos para mantención preventiva, control de temperatura y mejor ventilación.',
        'detalle' => 'Puede incluirse en servicio de mantención.',
        'precio' => 'Cotizar',
        'imagen' => 'assets/img/placa-tech.jpg',
        'badge' => 'Mantención',
        'destacado' => false,
    ],
    [
        'id' => 'perifericos-basicos',
        'categoria' => 'Periféricos',
        'nombre' => 'Mouse, teclado y periféricos',
        'descripcion' => 'Periféricos básicos para oficina, estudio, hogar o reemplazo rápido.',
        'detalle' => 'Cotización según disponibilidad y preferencia.',
        'precio' => 'Cotizar',
        'imagen' => 'assets/img/servicio-tecnico.jpeg',
        'badge' => 'Uso diario',
        'destacado' => false,
    ],
    [
        'id' => 'disco-respaldo',
        'categoria' => 'Almacenamiento',
        'nombre' => 'Discos para respaldo',
        'descripcion' => 'Opciones para respaldar documentos, fotos, trabajos y archivos importantes.',
        'detalle' => 'Se recomienda capacidad según volumen de datos.',
        'precio' => 'Cotizar',
        'imagen' => 'assets/img/soporte-tecnico.jpg',
        'badge' => 'Protege tus datos',
        'destacado' => false,
    ],
    [
        'id' => 'kit-upgrade',
        'categoria' => 'Combos',
        'nombre' => 'Combo upgrade equipo lento',
        'descripcion' => 'Combinación recomendada de SSD, RAM y mantención para recuperar rendimiento.',
        'detalle' => 'Se arma según diagnóstico y presupuesto.',
        'precio' => 'Cotizar',
        'imagen' => 'assets/img/diagnostico.jpeg',
        'badge' => 'Combo recomendado',
        'destacado' => true,
    ],
];

?>